# Generated by Django 5.2.7 on 2026-02-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('fuel', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('range_km', models.IntegerField()),
                ('gear', models.CharField(max_length=2)),
                ('song', models.CharField(max_length=100)),
            ],
        ),
    ]
